# Generated by Django 2.0.7 on 2025-02-20 22:59

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('gtitle', models.CharField(max_length=20, unique=True, verbose_name='goods_name')),
                ('gpic', models.ImageField(blank=True, null=True, upload_to='df_goods/image/%Y/%m', verbose_name='goods_pic')),
                ('gprice', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='goods_price')),
                ('gunit', models.CharField(default='500g', max_length=20, verbose_name='unit_weight')),
                ('gclick', models.IntegerField(default=0, verbose_name='click_count')),
                ('gjianjie', models.CharField(max_length=200, verbose_name='short_inro')),
                ('gkucun', models.IntegerField(default=0, verbose_name='stock')),
                ('gcontent', tinymce.models.HTMLField(max_length=200, verbose_name='descriptions')),
            ],
            options={
                'verbose_name': 'products',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='df_goods/images/%Y/%m', verbose_name='goods_pic')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='df_goods.GoodsInfo')),
            ],
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('ttitle', models.CharField(max_length=20, verbose_name='categories')),
                ('ntitle', models.CharField(max_length=50, verbose_name='category_name')),
            ],
            options={
                'verbose_name': 'product_category',
                'verbose_name_plural': 'product_category',
            },
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.TypeInfo', verbose_name='category'),
        ),
    ]
