# Generated by Django 5.1.6 on 2025-02-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("df_goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsinfo",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="typeinfo",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
