# Generated by Django 5.1.6 on 2025-02-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("df_goods", "0002_alter_goodsinfo_id_alter_productimage_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsinfo",
            name="gtitle",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="goods_name"
            ),
        ),
        migrations.AlterField(
            model_name="goodsinfo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
