# Generated by Django 4.2.19 on 2025-02-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0003_alter_goodsinfo_gtitle_alter_goodsinfo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsinfo',
            name='gpic',
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gprice_old',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='goods_price_old'),
        ),
    ]
