# Generated by Django 3.2.25 on 2025-03-12 06:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0004_remove_goodsinfo_gpic_goodsinfo_gprice_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='gparam',
            field=tinymce.models.HTMLField(default='', max_length=200, verbose_name='parameters'),
            preserve_default=False,
        ),
    ]
