# Generated by Django 2.0.7 on 2025-02-20 22:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsBrowser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Browse Time')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Browsing History',
                'verbose_name_plural': 'Browsing Histories',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('upwd', models.CharField(max_length=40, verbose_name='Password')),
                ('uemail', models.EmailField(max_length=254, verbose_name='Email')),
                ('ushou', models.CharField(default='', max_length=20, verbose_name='Shipping Address')),
                ('uaddress', models.CharField(default='', max_length=100, verbose_name='Address')),
                ('ufullname', models.CharField(default='', max_length=30, verbose_name='Full Name')),
                ('uyoubian', models.CharField(default='', max_length=6, verbose_name='Zip Code')),
                ('uphone', models.CharField(default='', max_length=11, verbose_name='Phone Number')),
                ('uanswer', models.CharField(default='', max_length=30, verbose_name='Security Answer')),
                ('uquestion', models.CharField(default='', max_length=40, verbose_name='Security Question')),
            ],
            options={
                'verbose_name': 'User_Info',
                'verbose_name_plural': 'User_Info',
            },
        ),
        migrations.AddField(
            model_name='goodsbrowser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo', verbose_name='User'),
        ),
    ]
