# Generated by Django 5.1.6 on 2025-02-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("df_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsbrowser",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
