# Generated by Django 5.1.6 on 2025-03-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("df_user", "0003_remove_userinfo_uemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="uaddress_detail",
            field=models.CharField(
                default="", max_length=100, verbose_name="Address Detail"
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="ucommune",
            field=models.CharField(default="", max_length=20, verbose_name="Commune"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="udistrict",
            field=models.CharField(default="", max_length=20, verbose_name="District"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="uprovince",
            field=models.CharField(default="", max_length=20, verbose_name="Province"),
        ),
    ]
