# Generated by Django 4.2.19 on 2025-03-05 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0004_userinfo_uaddress_detail_userinfo_ucommune_and_more'),
    ]

    operations = [
    ]
