# Generated by Django 4.2.19 on 2025-03-05 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0004_userinfo_uaddress_detail_userinfo_ucommune_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='uaddress_detail',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='ucommune',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='udistrict',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='uprovince',
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uprovince', models.CharField(default='', max_length=20, verbose_name='Province')),
                ('udistrict', models.CharField(default='', max_length=20, verbose_name='District')),
                ('ucommune', models.CharField(default='', max_length=20, verbose_name='Commune')),
                ('uaddress_detail', models.CharField(default='', max_length=100, verbose_name='Address Detail')),
                ('default_address_flg', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='df_user.userinfo')),
            ],
        ),
    ]
