# Generated by Django 3.2.25 on 2025-03-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0005_alter_userinfo_options_remove_userinfo_uaddress_and_more'),
        ('df_user', '0005_remove_userinfo_uaddress_detail_and_more'),
    ]

    operations = [
    ]
