# Generated by Django 3.2.25 on 2025-03-12 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0006_merge_20250312_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='uaddress',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='uaddress_detail',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='ucommune',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='udistrict',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='uprovince',
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uprovince', models.CharField(default='', max_length=20, verbose_name='Province')),
                ('udistrict', models.CharField(default='', max_length=20, verbose_name='District')),
                ('ucommune', models.CharField(default='', max_length=20, verbose_name='Commune')),
                ('uaddress_detail', models.CharField(default='', max_length=100, verbose_name='Address Detail')),
                ('default_address_flg', models.BooleanField(default=False, verbose_name='Default Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='df_user.userinfo', verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Addresses',
            },
        ),
    ]
