# Generated by Django 3.2.25 on 2025-03-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0007_auto_20250312_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is Admin'),
        ),
    ]
