# Generated by Django 2.0.7 on 2025-02-20 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_user', '0001_initial'),
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='goods_price')),
                ('count', models.IntegerField(verbose_name='goods_count')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo', verbose_name='products')),
            ],
            options={
                'verbose_name': 'order_details',
                'verbose_name_plural': 'order_details',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('oid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='order_no')),
                ('odate', models.DateTimeField(auto_now=True, verbose_name='order_time')),
                ('oIsPay', models.BooleanField(default=False, verbose_name='is_pay')),
                ('ototal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='total')),
                ('oaddress', models.CharField(default='', max_length=150, verbose_name='order_address')),
                ('oreceiver', models.CharField(default='', max_length=20, verbose_name='order_receiver')),
                ('ocontact', models.CharField(default='', max_length=11, verbose_name='receiver_phone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo', verbose_name='order_users')),
            ],
            options={
                'verbose_name': 'Orders',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.AddField(
            model_name='orderdetailinfo',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_order.OrderInfo', verbose_name='orders'),
        ),
    ]
