# Generated by Django 3.2.25 on 2025-03-21 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0007_auto_20250312_0650'),
        ('df_order', '0002_alter_orderdetailinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='df_user.userinfo', verbose_name='order_users'),
        ),
    ]
