# Generated by Django 3.2.25 on 2025-03-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0003_alter_orderinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='ototal',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='total'),
        ),
    ]
