# Generated by Django 3.2.25 on 2025-03-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0004_alter_orderinfo_ototal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailinfo',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='goods_price'),
        ),
    ]
