# Generated by Django 3.2.25 on 2025-03-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0005_alter_orderdetailinfo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='oIsDelivery',
            field=models.BooleanField(default=False, verbose_name='is_delivery'),
        ),
    ]
